core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf.urls.static import static                      # used for static files

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

    path('', include('homepage.urls')),
    path('inventory/', include('inventory.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    path('suppliers/', views.SupplierListView.as_view(), name='suppliers-list'),
    path('suppliers/new', views.SupplierCreateView.as_view(), name='new-supplier'),
    path('suppliers/<pk>/edit', views.SupplierUpdateView.as_view(), name='edit-supplier'),
    path('suppliers/<pk>/delete', views.SupplierDeleteView.as_view(), name='delete-supplier'),
    path('suppliers/<name>', views.SupplierView.as_view(), name='supplier'),

    path('purchases/', views.PurchaseView.as_view(), name='purchases-list'), 
    path('purchases/new', views.SelectSupplierView.as_view(), name='select-supplier'), 
    path('purchases/new/<pk>', views.PurchaseCreateView.as_view(), name='new-purchase'),    
    path('purchases/<pk>/delete', views.PurchaseDeleteView.as_view(), name='delete-purchase'),
     path('get-stock-perprice/<int:stock_id>/', views.get_stock_perprice, name='get-stock-perprice'),
    
    path('sales/', views.SaleView.as_view(), name='sales-list'),
    path('sales/new', views.SaleCreateView.as_view(), name='new-sale'),
    path('sales/<pk>/delete', views.SaleDeleteView.as_view(), name='delete-sale'),

    path("purchases/<billno>", views.PurchaseBillView.as_view(), name="purchase-bill"),
    path("sales/<billno>", views.SaleBillView.as_view(), name="sale-bill"),

    # path('get-stock-perprice/<int:stock_id>/', views.get_stock_perprice, name='get_stock_perprice'),

    
]

transactions/models.py
from django.db import models
from inventory.models import Stock

#contains suppliers
class Supplier(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=12, unique=True)
    address = models.CharField(max_length=200)
    email = models.EmailField(max_length=254, unique=True)
    
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
	    return self.name


#contains the purchase bills made
class PurchaseBill(models.Model):
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)
    supplier = models.ForeignKey(Supplier, on_delete = models.CASCADE, related_name='purchasesupplier')

    def __str__(self):
	    return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return PurchaseItem.objects.filter(billno=self)

    def get_total_price(self):
        purchaseitems = PurchaseItem.objects.filter(billno=self)
        total = 0
        for item in purchaseitems:
            total += item.totalprice
        return total

#contains the purchase stocks made
class PurchaseItem(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete = models.CASCADE, related_name='purchasebillno')
    stock = models.ForeignKey(Stock, on_delete = models.CASCADE, related_name='purchaseitem')
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    discount=models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)
    grand_total=models.IntegerField(default=1)
    net_amount=models.IntegerField(default=1)

    def __str__(self):
	    return "Bill no: " + str(self.billno.billno) + ", Item = " + self.stock.name

#contains the other details in the purchases bill
class PurchaseBillDetails(models.Model):
    billno = models.ForeignKey(PurchaseBill, on_delete = models.CASCADE, related_name='purchasedetailsbillno')
    
    
    
    destination = models.CharField(max_length=50, blank=True, null=True)
   
    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
	    return "Bill no: " + str(self.billno.billno)


#contains the sale bills made
class SaleBill(models.Model):
    billno = models.AutoField(primary_key=True)
    time = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=150)
    phone = models.CharField(max_length=12)
    address = models.CharField(max_length=200)
    email = models.EmailField(max_length=254)
   

    def __str__(self):
	    return "Bill no: " + str(self.billno)

    def get_items_list(self):
        return SaleItem.objects.filter(billno=self)
        
    def get_total_price(self):
        saleitems = SaleItem.objects.filter(billno=self)
        total = 0
        for item in saleitems:
            total += item.totalprice
        return total

#contains the sale stocks made
class SaleItem(models.Model):
    billno = models.ForeignKey(SaleBill, on_delete = models.CASCADE, related_name='salebillno')
    stock = models.ForeignKey(Stock, on_delete = models.CASCADE, related_name='saleitem')
    quantity = models.IntegerField(default=1)
    perprice = models.IntegerField(default=1)
    totalprice = models.IntegerField(default=1)

    discount=models.IntegerField(default=1)
    grand_total=models.IntegerField(default=1)
    net_amount=models.IntegerField(default=1)

    def __str__(self):
	    return "Bill no: " + str(self.billno.billno) + ", Item = " + self.stock.name

#contains the other details in the sales bill
class SaleBillDetails(models.Model):
    billno = models.ForeignKey(SaleBill, on_delete = models.CASCADE, related_name='saledetailsbillno')
    
   
    destination = models.CharField(max_length=50, blank=True, null=True)

    total = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
	    return "Bill no: " + str(self.billno.billno)

transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.http import JsonResponse
from django.forms import formset_factory
from django.contrib import messages


from .forms import PurchaseItemForm

from django.views.generic import (
    View, 
    ListView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import (
    PurchaseBill, 
    Supplier, 
    PurchaseItem,
    PurchaseBillDetails,
    SaleBill,  
    SaleItem,
    SaleBillDetails
)
from .forms import (
    SelectSupplierForm, 
    PurchaseItemFormset,
    PurchaseDetailsForm, 
    SupplierForm, 
    SaleForm,
    SaleItemFormset,
    SaleDetailsForm
)
from inventory.models import Stock




# shows a lists of all suppliers
class SupplierListView(ListView):
    model = Supplier
    template_name = "suppliers/suppliers_list.html"
    queryset = Supplier.objects.filter(is_deleted=False)
    paginate_by = 10


# used to add a new supplier
class SupplierCreateView(SuccessMessageMixin, CreateView):
    model = Supplier
    form_class = SupplierForm
    success_url = '/transactions/suppliers'
    success_message = "Supplier has been created successfully"
    template_name = "suppliers/edit_supplier.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'New Supplier'
        context["savebtn"] = 'Add Supplier'
        return context     


# used to update a supplier's info
class SupplierUpdateView(SuccessMessageMixin, UpdateView):
    model = Supplier
    form_class = SupplierForm
    success_url = '/transactions/suppliers'
    success_message = "Supplier details has been updated successfully"
    template_name = "suppliers/edit_supplier.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Edit Supplier'
        context["savebtn"] = 'Save Changes'
        context["delbtn"] = 'Delete Supplier'
        return context


# used to delete a supplier
class SupplierDeleteView(View):
    template_name = "suppliers/delete_supplier.html"
    success_message = "Supplier has been deleted successfully"

    def get(self, request, pk):
        supplier = get_object_or_404(Supplier, pk=pk)
        return render(request, self.template_name, {'object' : supplier})

    def post(self, request, pk):  
        supplier = get_object_or_404(Supplier, pk=pk)
        supplier.is_deleted = True
        supplier.save()                                               
        messages.success(request, self.success_message)
        return redirect('suppliers-list')


# used to view a supplier's profile
class SupplierView(View):
    def get(self, request, name):
        supplierobj = get_object_or_404(Supplier, name=name)
        bill_list = PurchaseBill.objects.filter(supplier=supplierobj)
        page = request.GET.get('page', 1)
        paginator = Paginator(bill_list, 10)
        try:
            bills = paginator.page(page)
        except PageNotAnInteger:
            bills = paginator.page(1)
        except EmptyPage:
            bills = paginator.page(paginator.num_pages)
        context = {
            'supplier'  : supplierobj,
            'bills'     : bills
        }
        return render(request, 'suppliers/supplier.html', context)




# shows the list of bills of all purchases 
class PurchaseView(ListView):
    model = PurchaseBill
    template_name = "purchases/purchases_list.html"
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


# used to select the supplier
class SelectSupplierView(View):
    form_class = SelectSupplierForm
    template_name = 'purchases/select_supplier.html'

    def get(self, request, *args, **kwargs):                                    # loads the form page
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):                                   # gets selected supplier and redirects to 'PurchaseCreateView' class
        form = self.form_class(request.POST)
        if form.is_valid():
            supplierid = request.POST.get("supplier")
            supplier = get_object_or_404(Supplier, id=supplierid)
            return redirect('new-purchase', supplier.pk)
        return render(request, self.template_name, {'form': form})

# views.py


def get_stock_perprice(request, stock_id):
    stock = get_object_or_404(Stock, id=stock_id)

    # Assuming your Stock model has a 'price' field
    perprice = stock.price

    return JsonResponse({'perprice': perprice})





class PurchaseCreateView(View):
    template_name = 'purchases/new_purchase.html'

    def calculate_grand_total(self, purchase_items):
        grand_total = 0
        for item in purchase_items:
            grand_total += item.net_amount
        return grand_total

    def get(self, request, pk):
        formset = PurchaseItemFormset(request.GET or None)
        hes = Stock.objects.all()
        stock_prices = {stock.id: stock.price for stock in Stock.objects.all()}

        supplierobj = get_object_or_404(Supplier, pk=pk)
        context = {
            'formset': formset,
            'supplier': supplierobj,
            'hes': hes,
            'stock_prices': stock_prices,
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        purchase_items = []
        formset = PurchaseItemFormset(request.POST)
        supplierobj = get_object_or_404(Supplier, pk=pk)

        if formset.is_valid():
            with transaction.atomic():
                billobj = PurchaseBill(supplier=supplierobj)
                billobj.save()

                billdetailsobj = PurchaseBillDetails(billno=billobj)
                billdetailsobj.save()

                grand_total = 0

                for form in formset:
                    purchaseitem = form.save(commit=False)
                    purchaseitem.billno = billobj

                    stock = get_object_or_404(Stock, name=purchaseitem.stock)
                    x=stock.price

                    # Automatically set perprice based on the selected stock's price
                    purchaseitem.perprice = stock.price
                    

                    purchaseitem.save()

                    purchaseitem.totalprice = purchaseitem.perprice * purchaseitem.quantity

                    # Simplified net_amount calculation
                    purchaseitem.net_amount = purchaseitem.totalprice * (1 - purchaseitem.discount / 100)

                    stock.quantity += purchaseitem.quantity
                    stock.save()

                    grand_total += purchaseitem.net_amount

                    purchase_items.append(purchaseitem)
                    purchaseitem.grand_total = self.calculate_grand_total(purchase_items)
                    purchaseitem.save()

                billobj.grand_total = grand_total
                billobj.save()

                # Calculate perprices for each stock and send them as JSON response
                stock_perprices = {stock.id: stock.price for stock in Stock.objects.all()}
                return redirect('purchase-bill', billno=billobj.billno)

        formset = PurchaseItemFormset(request.GET or None)
        context = {
            'formset': formset,
            'supplier': supplierobj
        }
        return render(request, self.template_name, context)

# Create a PurchaseItem formset with the PurchaseItemForm
PurchaseItemFormset = formset_factory(PurchaseItemForm, extra=1)

# ... (your existing code)


# used to delete a bill object
class PurchaseDeleteView(SuccessMessageMixin, DeleteView):
    model = PurchaseBill
    template_name = "purchases/delete_purchase.html"
    success_url = '/transactions/purchases'
    
    def delete(self, *args, **kwargs):
        self.object = self.get_object()
        items = PurchaseItem.objects.filter(billno=self.object.billno)
        for item in items:
            stock = get_object_or_404(Stock, name=item.stock.name)
            if stock.is_deleted == False:
                stock.quantity -= item.quantity
                stock.save()
        messages.success(self.request, "Purchase bill has been deleted successfully")
        return super(PurchaseDeleteView, self).delete(*args, **kwargs)




# shows the list of bills of all sales 
class SaleView(ListView):
    model = SaleBill
    template_name = "sales/sales_list.html"
    context_object_name = 'bills'
    ordering = ['-time']
    paginate_by = 10


# used to generate a bill object and save items
class SaleCreateView(View):
    template_name = 'sales/new_sale.html'

    def calculate_grand_total(self, sale_items):
        grand_total = 0
        for item in sale_items:
            grand_total += item.net_amount
        return grand_total

    def get(self, request):
        form = SaleForm(request.GET or None)
        formset = PurchaseItemFormset(request.GET or None)
        hes = Stock.objects.all()
        stock_prices = {stock.id: stock.price for stock in Stock.objects.all()}

        context = {
            'form': form,
            'formset': formset,
            'stock_prices': stock_prices,
            'hes': hes,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        sale_items = []   
        form = SaleForm(request.POST)
        formset = SaleItemFormset(request.POST)

        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                billobj = form.save(commit=False)
                billobj.save()

                billdetailsobj = SaleBillDetails(billno=billobj)
                billdetailsobj.save()

transactions/templates/purchases/delete_purchase.html
{% extends "base.html" %}


{% block title %} Delete Purchase {% endblock title %}


{% block content %}
                
    <form method="post">
        
        {% csrf_token %}
        
        <fieldset class="form-group">
            <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">Delete Purchase Bill</div> <br>
            <h2 style="color:#575757;">Are you sure you want to delete the Purchase Bill No: {{ object.billno }}?</h2>
        </fieldset>

        <div class="form-group">  
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}

transactions/templates/purchases/new_purchase.html
{% extends "base.html" %}
{% load static %}


{% block title %} New Purchase {% endblock title %}


{% block content %}



    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div>
    
        <br><!-- Log on to codeastro.com for more projects -->
        

        <div class="panel panel-default">
            <div class="panel-heading panel-heading-text">Supplier Details</div>
            <div class="panel-body">
                    
                <div class="form-group">
                    <label for="id_name" class="panel-body-text">Supplier Name:</label>
                    <input type="text" class="form-control textinput" id="id_name" value="{{ supplier.name }}" disabled>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_phone" class="panel-body-text">Phone No:</label>
                        <input type="text" class="form-control textinput" id="id_phone" value="{{ supplier.phone }}" disabled>
                    </div>
                    <!-- <div class="form-group col-md-6">
                        <label for="id_gstin" class="panel-body-text">GSTIN No:</label>
                        <input type="gstin" class="form-control textinput" id="id_gstin" value="{{ supplier.gstin }}" disabled>
                    </div> -->
                </div>

            </div><!-- Log on to codeastro.com for more projects -->
        </div>

        <br>
        <h1 style="color: rgb(49, 46, 46);">check your product price</h1>
        <select id="itemDropdown" onchange="displayPrice()">
            {% for i in hes %}
                <option value="{{ i.name }}" data-price="{{ i.price }}">{{ i.name }}</option>
            {% endfor %}
        </select>
        <p id="selectedPrice">Selected Price: </p>

        <form method="post" class="panel panel-default">
            
            {% csrf_token %}
            {{ formset.management_form }}

            <div class="panel-heading panel-heading-text">Product Details</div>
            
                <div id="stockitem"> 
                    <div class="panel-body">
                    {% for form in formset %}
                        <div class="row form-row">
                            <div class="form-group col-md-3">
                                {{ form.stock.errors }}
                                <label class="panel-body-text">Stock:</label>

                                
                                {{ form.stock }}
                               
                            </div><!-- Log on to codeastro.com for more projects -->
                            <div class="form-group col-md-2">
                                <label class="panel-body-text" >Price per item:</label>
                               {{form.perprice}}
                            </div>
                            
                        
                            <div class="form-group col-md-2">
                                {{ form.quantity.errors }}
                                <label class="panel-body-text">Quantity:</label>
                                {{ form.quantity }}
                            </div><!-- Log on to codeastro.com for more projects -->

                            <div class="form-group col-md-2">
                                <label class="panel-body-text">Discount:</label>
                                {{ form.discount }}
                            </div>

                            <div class="form-group col-md-1">
                                <label class="panel-body-text">Price:</label>
                                <input type="text" class="textinput form-control totalprice" value="1" disabled required>
                            </div>

                            <div class="form-group col-md-1">
                                <label class="panel-body-text">Discounted:</label>
                                <input type="text" class="textinput form-control discounted-price" value="0.00" disabled required>
                            </div>
          
                            <div class="form-group col-md-1">
                                <label class="panel-body-text" style="color: #000">.</label>
                                <button class="form-control btn btn-danger remove-form-row">-</button>
                            </div>
                        </div>
                    {% endfor %}

                        <div style="text-align: right;">                    
                            <a href="#" class="add-form-row">+ Add More</a>
                        </div>
                    </div>
                </div>
              


            <br><!-- Log on to codeastro.com for more projects -->

            <div class="align-middle">
                <button type="submit" class="btn btn-success">Add to Purchases</button>
                <a href="{% url 'select-supplier' %}" class="btn btn-danger">Go Back</a>
                <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
            </div>
            
        </form>
        
        
       
        
        
        <!-- {% for i in hes %}
        <h2 style="color: black;">{{i.name}}:{{i.price}}</h2>

        {% endfor %} -->

    </div>
    <!-- At the end of your HTML file, before the closing </body> tag -->
    <!-- At the end of your HTML file, before the closing </body> tag -->
    <script>
        function displayPrice() {
            // Get the selected item and its price
            var selectedValue = document.getElementById("itemDropdown").value;
            var selectedOption = document.getElementById("itemDropdown").options[document.getElementById("itemDropdown").selectedIndex];
            var selectedPrice = selectedOption.getAttribute("data-price");
    
            // Display the selected item and its price
            
            document.getElementById("selectedPrice").innerText = "Selected Price: " + selectedPrice;
            // document.getElementById("price").value =selectedPrice;

        }
    </script>

<!-- <script>
    function displayPrice1() {
        // Get the selected item and its price
        var selectedValue = document.getElementById("itemDropdown").value;
        var selectedOption = document.getElementById("itemDropdown").options[document.getElementById("itemDropdown").selectedIndex];
        var selectedPrice = selectedOption.getAttribute("data-price");

        // Display the selected item and its price
        document.getElementById("selectedPrice").innerText = "Selected Price: " + selectedPrice;
        document.getElementById("price").value =selectedPrice;

    }
</script> -->


    <script>
        $(document).ready(function () {
            // Add data-form-index attribute to stock fields
            $('.stock').each(function (index, element) {
                $(element).attr('data-form-index', index);
            });

            // Event listener for the change event of the stock dropdown
            $('.stock').on('change', function () {
                var stockId = $(this).val();
                var formIndex = $(this).data('form-index');
                var perpriceField = $('#id_form-' + formIndex + '-perprice');
                var perpriceDisplay = $('.perprice-display[data-form-index="' + formIndex + '"]');

                // Make an AJAX request to get the perprice for the selected stock
                $.ajax({
                    url: '/get-stock-perprice/' + stockId + '/',  // Replace with your actual URL
                    type: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        // Update the perprice field with the received data
                        perpriceField.val(data.perprice);
                        // Update the perprice display span
                        perpriceDisplay.text(data.perprice);
                    },
                    error: function () {
                        // Handle errors if necessary
                    }
                });
            });

            // Rest of your JavaScript code...
        });
    </script>


    <!-- Custom JS to add and remove item forms --><!-- Log on to codeastro.com for more projects -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/dialogbox.js' %}"></script>
    <script type="text/javascript">
        
        //creates custom alert object
        var custom_alert = new custom_alert();

        function updateElementIndex(el, prefix, ndx) {
            var id_regex = new RegExp('(' + prefix + '-\\d+)');
            var replacement = prefix + '-' + ndx;
            if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
            if (el.id) el.id = el.id.replace(id_regex, replacement);
            if (el.name) el.name = el.name.replace(id_regex, replacement);
        }
        
        //stores the total no of item forms
        var total = 1;

        function cloneMore(selector, prefix) {
            var newElement = $(selector).clone(true);
            //var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
            newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
                var name = $(this).attr('name')
                if(name) {
                    name = name.replace('-' + (total-1) + '-', '-' + total + '-');
                    var id = 'id_' + name;
                    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
                }
            });
            newElement.find('label').each(function() {
                var forValue = $(this).attr('for');
                if (forValue) {
                forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
                $(this).attr({'for': forValue});
                }
            });
            total++;
            $('#id_' + prefix + '-TOTAL_FORMS').val(total);
            $(selector).after(newElement);
            return false;
        }
        
        function deleteForm(prefix, btn) {
            //var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
            if (total > 1){
                btn.closest('.form-row').remove();
                var forms = $('.form-row');
                $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
                for (var i=0, formCount=forms.length; i<formCount; i++) {
                    $(forms.get(i)).find(':input').each(function() {
                        updateElementIndex(this, prefix, i);
                    });
                }
                total--;
            } else {
                custom_alert.render("Field cannot be deleted");
            }
            return false;
        }
        
        $(document).on('click', '.add-form-row', function(e){
            e.preventDefault();
            cloneMore('.form-row:last', 'form');
            return false;
        });
        
        $(document).on('click', '.remove-form-row', function(e){
            e.preventDefault();
            deleteForm('form', $(this));
            return false;
        });


        //updates the total price by multiplying 'price per item' and 'quantity' 
        $(document).on('change', '.setprice', function(e){
            e.preventDefault();
            //gets the values
            var element = $(this);
            var quantity = element.parents('.form-row').find('.quantity').val();
            var perprice = element.parents('.form-row').find('.price').val();
            //calculates the total
            var tprice = quantity * perprice;
            //sets it to field
            element.parents('.form-row').find('.totalprice').val(tprice);
            return false;
        });

        // Event listener to calculate and update the discounted price when the total price changes
    $(document).on('input', '.quantity, .price, .discount', function(e) {
        e.preventDefault();
        calculateDiscountedPrice($(this));
        return false;
    });

    // Function to calculate discounted price and update the field
    function calculateDiscountedPrice(element) {
        var quantity = parseFloat(element.parents('.form-row').find('.quantity').val());
        var price = parseFloat(element.parents('.form-row').find('.price').val());
        var discount = parseFloat(element.parents('.form-row').find('.discount').val());

        // Calculate the total price
        var totalPrice = quantity * price;

        // Calculate the discounted price
        var discountedPrice = totalPrice - (totalPrice * (discount / 100));

        // Set the calculated discounted price in the corresponding field
        element.parents('.form-row').find('.discounted-price').val(discountedPrice.toFixed(2));
    }



    </script>

{% endblock content %}

transactions/templates/purchases/select_supplier.html
{% extends "base.html" %}


{% block title %} New Purchase {% endblock title %}


{% block content %}

    <div style="color:#575757; font-style: bold; font-size: 3rem; border-bottom: 1px solid white;">New Purchase</div> 
    
    <br>
    
    <form method="post">

        {% csrf_token %}
        
        {% for field in form.visible_fields %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}

        <br>
        <div class="align-middle">
            <button type="submit" class="btn btn-success">Next</button>
            <a href="{% url 'purchases-list' %}" class="btn btn-secondary">Cancel</a>
        </div>
        
    </form>

{% endblock content %}